config/routes.rb
Rails.application.routes.draw do
  resources :todos
  post '/todos/:id/toggle', to: 'todos#toggle', as: :toggle_todo  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :content, presence: true

  # broadcasts
  after_destroy_commit -> { broadcast_remove_to :todos }
  after_create_commit -> { broadcast_append_to :todos }
  after_update_commit -> { broadcast_replace_to :todos }


  def toggle
    self.completed = !self.completed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[show edit update destroy toggle]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show; end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)
    notice = 'Todo was successfully created.'

    respond_to do |format|
      if @todo.save
        format.turbo_stream { render :create, locals: { notice: notice } }
        format.html { redirect_to todos_path, notice: notice }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    @notice = 'Todo was successfully updated.'
    respond_to do |format|
      if @todo.update(todo_params)
        format.turbo_stream
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy
    notice = 'Todo was successfully destroyed.'

    respond_to do |format|
      format.turbo_stream { render :destroy, locals: { notice: notice } }
      format.html { redirect_to todos_url, notice: notice }
    end
  end

  def toggle
    @todo.completed = params.require(:todo).permit(:completed)[:completed]
    respond_to do |format|
      if @todo.save
        format.turbo_stream
        format.html { redirect_to todos_url }
      else
        format.html { redirect_to todos_url }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_todo
    @todo = Todo.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def todo_params
    params.require(:todo).permit(:content, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoHotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
    <div class="container mt-6">
      <%= yield %>
    </div>
  </body>
</html>

app/views/todos/_form.html.erb
<%= turbo_frame_tag "todo" do %>
  <%= form_with model: todo do |form| %>
    <div
        class="panel-block is-flex is-flex-direction-row is-justify-content-center"
      >
      <%= form.text_field :content, class: "input #{'is-danger' if todo.errors[:content].any?}", placeholder: "Type your next todo" %>
      <% if todo.errors[:content].any? %> 
        <p> <%= todo.errors[:content].first %> </p>
      <% end %>
    </div>
    <div class="panel-block">
      <button class="button is-primary is-fullwidth">Adicionar</button>
    </div>
  <% end %>
<% end %>

app/views/todos/_todo.html.erb
<div
  class="panel-block is-flex is-flex-direction-row is-justify-content-space-between"
  id="<%= dom_id todo %>"
>
  <%= form_with model: todo, url: toggle_todo_path(todo), data: {controller:
  :'complete-task', 'complete-task-target': :form}, method: :post do |form| %>
    <label class="checkbox">
      <%= form.check_box :completed, data: {action: :'complete-task#toggle'} %> 
      <%= todo.content %>
    </label>
  <% end %>
  <div class="is-flex">
    <%= button_to todo, method: :delete, class: "button is-white
    is-small" do %>
      <i class="fas fa-trash"></i>
    <% end %>
  </div>
</div>

app/views/todos/create.turbo_stream.erb
<%= turbo_stream.replace "todo" do %>
  <%= render partial: 'form', locals: { todo: Todo.new } %>
<% end %>

<%= turbo_stream.update "notice" do %>
  <% if notice.present? %>
    <div class="notification is-info">
      <%= notice %>
    </div>
  <% end %>
<% end %>

app/views/todos/destroy.turbo_stream.erb
<%= turbo_stream.update "notice" do %>
  <% if notice.present? %>
    <div class="notification is-info">
      <%= notice %>
    </div>
  <% end %>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/edit.turbo_stream.erb
<%= turbo_stream.replace @todo do %>
  <div
    class="panel-block is-flex is-flex-direction-row is-justify-content-space-between"
    id="<%= dom_id @todo %>"
  >
    <%= form_with model: @todo do |form| %>
      <%= form.text_field :content, class: "input #{'is-danger' if @todo.errors[:content].any?}", placeholder: "Type your next todo" %>
      <% if @todo.errors[:content].any? %> 
        <p> <%= @todo.errors[:content].first %> </p>
      <% end %>
      <button class="button is-primary is-fullwidth">Adicionar</button>
    <% end %>
  </div>
<% end %>

app/views/todos/index.html.erb
<%= turbo_stream_from :todos %>

<div class="columns is-centered">
  <div
    class="column is-two-thirds-tablet is-half-desktop is-one-third-widescreen"
  >
    
    <div id="notice" >
      <% if notice.present? %>
        <div class="notification is-info">
          <%= notice %>
        </div>
      <% end %>
    </div>
    

    <div class="panel mt-2">
      <h1 class="panel-heading">Todos</h1>
      <div id="todos">
        <%= render partial: :todo, collection: @todos %>    
      </div>

      <%= turbo_frame_tag :todo, src: new_todo_path do %>
        <div
          class="panel-block is-flex is-flex-direction-row is-justify-content-center"
        >
          <div class="is-flex">
            <p class="is-size-3 has-text-centered">
              <i class="fas fa-circle-notch fa-spin"></i>
            </p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<br />

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @todo.content %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo.completed %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/todos/update.turbo_stream.erb
<%= #turbo_stream.update @todo %>